modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "CC BY 4.0"

[[mods]]
modId = "placeablemaxwell"
version = "${version}"
displayName = "Maxwell the placeable cat"
authors = "Flowyan"
description = '''
Adds Maxwell the placeable cat.
'''
logoFile = "maxwell.png"

[[dependencies.placeablemaxwell]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeablemaxwell]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeablemaxwell]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
